export const autocontrolData = [
  {
    nACId: 1,
    szLineName: 'Line 1',
    szACName: 'Videojet LATA Line 1',
    szArea: 'Area 1',
    nStatus: 1,
    szStatus: 'Created',
    szComment: 'Comment 1',
    tLastModified: new Date(2021, 3, 21),
  },
  {
    nACId: 2,
    szLineName: 'Line 2',
    szACName: 'Videojet LATA Line 2',
    szArea: 'Area 1',
    nStatus: 1,
    szStatus: 'Created',
    szComment: 'Comment 2',
    tLastModified: new Date(2022, 3, 22),
  },
  {
    nACId: 3,
    szLineName: 'Line 3',
    szACName: 'Videojet LATA Line 3',
    szArea: 'Area 3',
    nStatus: 2,
    szStatus: 'Complete',
    szComment: 'Comment 3',
    tLastModified: new Date(2023, 3, 23),
  },
  {
    nACId: 4,
    szLineName: 'Line 4',
    szACName: 'Videojet LATA Line 4',
    szArea: 'Area 4',
    nStatus: 2,
    szStatus: 'Complete',
    szComment: 'Comment 4',
    tLastModified: new Date(2024, 3, 24),
  },
  {
    nACId: 5,
    szLineName: 'Line 5',
    szACName: 'Videojet LATA Line 5',
    szArea: 'Area 5',
    nStatus: 2,
    szStatus: 'Complete',
    szComment: 'Comment 5',
    tLastModified: new Date(2025, 3, 25),
  }]
